# Generated by Django 5.1.1 on 2024-09-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Overall'),
            preserve_default=False,
        ),
    ]
