# Generated by Django 5.1.1 on 2024-09-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_attackworkrate_player_club_player_defending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='attackWorkRate',
            field=models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto')], default='M', max_length=6, verbose_name='Dedicação Ofensiva'),
        ),
        migrations.AlterField(
            model_name='player',
            name='defenseWorkRate',
            field=models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto')], default='M', max_length=6, verbose_name='Dedicação Defensiva'),
        ),
        migrations.AlterField(
            model_name='player',
            name='foot',
            field=models.CharField(choices=[('left', 'Esquerdo'), ('right', 'Direito')], default='D', max_length=5, verbose_name='Pé Dominante'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], default='M', max_length=6, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goleiro'), ('CB', 'Zagueiro'), ('LB', 'Lateral Esquerdo'), ('RB', 'Lateral Direito'), ('LWB', 'Lateral Esquerdo Ofensivo'), ('RWB', 'Lateral Direito Ofensivo'), ('CDM', 'Volante'), ('CM', 'Meio Campo'), ('CAM', 'Meia Atacante'), ('LM', 'Meia Lateral Esquerdo'), ('RM', 'Meia Lateral Direito'), ('LW', 'Ponta Esquerda'), ('RW', 'Ponta Direita'), ('ST', 'Atacante'), ('CA', 'Centroavante')], default='GOL', max_length=3, verbose_name='Posição'),
        ),
    ]
